<?xml version="1.0"?>
<model xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" modelName="D:\AsTeRICS\AsTeRICS_singleThreadedStabilization\AsTeRICS\Tests\integrationTests\04_Model execution\EventAHang10sec.acs_2015_3_17_14_45" version="20130320">
  <modelDescription>
    <shortDescription />
    <requirements />
    <description />
  </modelDescription>
  <components>
    <component id="EmulateFaultyPlugin.2" type_id="asterics.EmulateFaultyPlugin">
      <description>Emulates a faulty plugin - supports throwing exceptions during method calls or hanging (unresponsive) method calls </description>
      <ports>
        <inputPort portTypeID="inA">
          <properties />
        </inputPort>
        <inputPort portTypeID="inB" sync="false">
          <properties />
        </inputPort>
        <inputPort portTypeID="inC">
          <properties />
        </inputPort>
        <inputPort portTypeID="inD">
          <properties />
        </inputPort>
      </ports>
      <properties>
        <property name="startException" value="False" />
        <property name="pauseException" value="false" />
        <property name="resumeException" value="false" />
        <property name="stopException" value="false" />
        <property name="getInputPortException" value="false" />
        <property name="getOutputPortException" value="false" />
        <property name="getRuntimePropertyValueException" value="false" />
        <property name="setRuntimePropertyValueException" value="false" />
        <property name="getEventListenerPortException" value="false" />
        <property name="getInputPortNullValue" value="false" />
        <property name="getOutputPortNullValue" value="false" />
        <property name="getRuntimePropertyNullValue" value="false" />
        <property name="getEventListenerPortNullValue" value="false" />
        <property name="startDuration" value="0" />
        <property name="pauseDuration" value="0" />
        <property name="resumeDuration" value="0" />
        <property name="stopDuration" value="0" />
        <property name="getRuntimePropertyDuration" value="0" />
        <property name="setRuntimePropertyDuration" value="0" />
        <property name="inADuration" value="0" />
        <property name="inBDuration" value="0" />
        <property name="inCDuration" value="0" />
        <property name="inDDuration" value="0" />
        <property name="eventADuration" value="10000" />
        <property name="eventBDuration" value="0" />
        <property name="eventCDuration" value="0" />
      </properties>
      <layout>
        <posX>255</posX>
        <posY>143</posY>
      </layout>
      <gui>
        <posX>125</posX>
        <posY>667</posY>
        <width>30</width>
        <height>20</height>
      </gui>
    </component>
    <component id="ConstantDispatcher.1" type_id="asterics.ConstantDispatcher">
      <description>Send double values from chosen slot</description>
      <ports>
        <inputPort portTypeID="slotDispatch">
          <properties />
        </inputPort>
        <outputPort portTypeID="output">
          <properties />
        </outputPort>
      </ports>
      <properties>
        <property name="number" value="20" />
        <property name="delay" value="300" />
        <property name="slot1" value="20" />
        <property name="slot2" value="0" />
        <property name="slot3" value="0" />
        <property name="slot4" value="0" />
        <property name="slot5" value="0" />
        <property name="slot6" value="0" />
        <property name="slot7" value="0" />
        <property name="slot8" value="0" />
        <property name="slot9" value="0" />
        <property name="slot10" value="0" />
        <property name="slot11" value="0" />
        <property name="slot12" value="0" />
        <property name="slot13" value="0" />
        <property name="slot14" value="0" />
        <property name="slot15" value="0" />
        <property name="slot16" value="0" />
        <property name="slot17" value="0" />
        <property name="slot18" value="0" />
        <property name="slot19" value="0" />
        <property name="slot20" value="0" />
        <property name="autosendSlot" value="0" />
      </properties>
      <layout>
        <posX>115</posX>
        <posY>125</posY>
      </layout>
    </component>
    <component id="ButtonGrid.1" type_id="asterics.ButtonGrid">
      <description>Keyboard which sends event after button press</description>
      <ports />
      <properties>
        <property name="caption" value="Keyboard" />
        <property name="horizontalOrientation" value="false" />
        <property name="textColor" value="13" />
        <property name="backgroundColor" value="13" />
        <property name="borderColor" value="13" />
        <property name="borderThickness" value="2" />
        <property name="selectionFrameColor" value="13" />
        <property name="selectionFrameThickness" value="4" />
        <property name="displayGUI" value="True" />
        <property name="buttonCaption1" value="Send Data" />
        <property name="buttonCaption2" value="" />
        <property name="buttonCaption3" value="" />
        <property name="buttonCaption4" value="" />
        <property name="buttonCaption5" value="" />
        <property name="buttonCaption6" value="" />
        <property name="buttonCaption7" value="" />
        <property name="buttonCaption8" value="" />
        <property name="buttonCaption9" value="" />
        <property name="buttonCaption10" value="" />
        <property name="buttonCaption11" value="" />
        <property name="buttonCaption12" value="" />
        <property name="buttonCaption13" value="" />
        <property name="buttonCaption14" value="" />
        <property name="buttonCaption15" value="" />
        <property name="buttonCaption16" value="" />
        <property name="buttonCaption17" value="" />
        <property name="buttonCaption18" value="" />
        <property name="buttonCaption19" value="" />
        <property name="buttonCaption20" value="" />
        <property name="toolTip1" value="" />
        <property name="toolTip2" value="" />
        <property name="toolTip3" value="" />
        <property name="toolTip4" value="" />
        <property name="toolTip5" value="" />
        <property name="toolTip6" value="" />
        <property name="toolTip7" value="" />
        <property name="toolTip8" value="" />
        <property name="toolTip9" value="" />
        <property name="toolTip10" value="" />
        <property name="toolTip11" value="" />
        <property name="toolTip12" value="" />
        <property name="toolTip13" value="" />
        <property name="toolTip14" value="" />
        <property name="toolTip15" value="" />
        <property name="toolTip16" value="" />
        <property name="toolTip17" value="" />
        <property name="toolTip18" value="" />
        <property name="toolTip19" value="" />
        <property name="toolTip20" value="" />
      </properties>
      <layout>
        <posX>0</posX>
        <posY>257</posY>
      </layout>
      <gui>
        <posX>250</posX>
        <posY>667</posY>
        <width>500</width>
        <height>2000</height>
      </gui>
    </component>
    <component id="TextDisplay.1" type_id="asterics.TextDisplay">
      <description>GUI component, which displays text.</description>
      <ports>
        <inputPort portTypeID="input">
          <properties />
        </inputPort>
      </ports>
      <properties>
        <property name="caption" value="Text Display" />
        <property name="default" value="" />
        <property name="textPosition" value="1" />
        <property name="textColor" value="0" />
        <property name="backgroundColor" value="11" />
        <property name="displayGUI" value="true" />
      </properties>
      <layout>
        <posX>267</posX>
        <posY>343</posY>
      </layout>
      <gui>
        <posX>822</posX>
        <posY>676</posY>
        <width>3000</width>
        <height>2000</height>
      </gui>
    </component>
  </components>
  <channels>
    <channel id="binding.1">
      <source>
        <component id="ConstantDispatcher.1" />
        <port id="output" />
      </source>
      <target>
        <component id="TextDisplay.1" />
        <port id="input" />
      </target>
    </channel>
  </channels>
  <eventChannels>
    <eventChannel id="button1_eventA">
      <description />
      <sources>
        <source>
          <component id="ButtonGrid.1" />
          <eventPort id="button1" />
        </source>
      </sources>
      <targets>
        <target>
          <component id="EmulateFaultyPlugin.2" />
          <eventPort id="eventA" />
        </target>
      </targets>
    </eventChannel>
    <eventChannel id="button1_dispatchSlot1">
      <description />
      <sources>
        <source>
          <component id="ButtonGrid.1" />
          <eventPort id="button1" />
        </source>
      </sources>
      <targets>
        <target>
          <component id="ConstantDispatcher.1" />
          <eventPort id="dispatchSlot1" />
        </target>
      </targets>
    </eventChannel>
  </eventChannels>
  <modelGUI>
    <Decoration>true</Decoration>
    <Fullscreen>false</Fullscreen>
    <AlwaysOnTop>false</AlwaysOnTop>
    <ToSystemTray>false</ToSystemTray>
    <ShopControlPanel>true</ShopControlPanel>
    <AREGUIWindow>
      <posX>125</posX>
      <posY>267</posY>
      <width>9000</width>
      <height>5000</height>
    </AREGUIWindow>
  </modelGUI>
</model>