<?xml version="1.0"?>
<model xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" modelName="D:\AsTeRICS\AsTeRICS_master\AsTeRICS\Tests\integrationTests\04_Model execution\HangWithCellBoard.acs_2015_3_20_23_52" version="20130320">
  <modelDescription>
    <shortDescription>A menu selection for some demo models which do not need special hardware.</shortDescription>
    <requirements>none</requirements>
    <description>The Cellboard plugin is used as an On-Screen selection with automatic scanning. The desired Model can be started by pressing the Spacebar key on the keyboard.</description>
  </modelDescription>
  <components>
    <component id="CellBoard.1" type_id="asterics.CellBoard">
      <description>Adjustable matrix of button cells with scanning support</description>
      <ports>
        <inputPort portTypeID="row">
          <properties />
        </inputPort>
        <inputPort portTypeID="column">
          <properties />
        </inputPort>
        <inputPort portTypeID="cellNumber">
          <properties />
        </inputPort>
        <inputPort portTypeID="xmlFile">
          <properties />
        </inputPort>
        <outputPort portTypeID="actCell">
          <properties />
        </outputPort>
        <outputPort portTypeID="actCellCaption">
          <properties />
        </outputPort>
        <outputPort portTypeID="actCellText">
          <properties />
        </outputPort>
        <outputPort portTypeID="selectedCell">
          <properties />
        </outputPort>
        <outputPort portTypeID="selectedCellCaption">
          <properties />
        </outputPort>
        <outputPort portTypeID="selectedCellText">
          <properties />
        </outputPort>
      </ports>
      <properties>
        <property name="caption" value="" />
        <property name="rows" value="5" />
        <property name="columns" value="0" />
        <property name="textColor" value="3" />
        <property name="backgroundColor" value="11" />
        <property name="scanColor" value="10" />
        <property name="scanMode" value="0" />
        <property name="hoverTime" value="1000" />
        <property name="enableEdit" value="true" />
        <property name="enableClickSelection" value="true" />
        <property name="keyboardFile" value="" />
        <property name="displayGUI" value="true" />
        <property name="cellText1" value="CameraMouse" />
        <property name="cellImage1" value="" />
        <property name="actionText1" value="" />
        <property name="cellText2" value="OskaWriting" />
        <property name="cellImage2" value="" />
        <property name="actionText2" value="" />
        <property name="cellText3" value="SpeechControl" />
        <property name="cellImage3" value="" />
        <property name="actionText3" value="" />
        <property name="cellText4" value="GamepadMouse" />
        <property name="cellImage4" value="" />
        <property name="actionText4" value="" />
        <property name="cellText5" value="ImageDemo" />
        <property name="cellImage5" value="" />
        <property name="actionText5" value="" />
        <property name="cellText6" value="Ergotherapie" />
        <property name="cellImage6" value="" />
        <property name="actionText6" value="" />
        <property name="cellText7" value="" />
        <property name="cellImage7" value="" />
        <property name="actionText7" value="" />
        <property name="cellText8" value="" />
        <property name="cellImage8" value="" />
        <property name="actionText8" value="" />
        <property name="cellText9" value="" />
        <property name="cellImage9" value="" />
        <property name="actionText9" value="" />
        <property name="cellText10" value="" />
        <property name="cellImage10" value="" />
        <property name="actionText10" value="" />
        <property name="cellText11" value="" />
        <property name="cellImage11" value="" />
        <property name="actionText11" value="" />
        <property name="cellText12" value="" />
        <property name="cellImage12" value="" />
        <property name="actionText12" value="" />
        <property name="cellText13" value="" />
        <property name="cellImage13" value="" />
        <property name="actionText13" value="" />
        <property name="cellText14" value="" />
        <property name="cellImage14" value="" />
        <property name="actionText14" value="" />
        <property name="cellText15" value="" />
        <property name="cellImage15" value="" />
        <property name="actionText15" value="" />
        <property name="cellText16" value="" />
        <property name="cellImage16" value="" />
        <property name="actionText16" value="" />
        <property name="cellText17" value="" />
        <property name="cellImage17" value="" />
        <property name="actionText17" value="" />
        <property name="cellText18" value="" />
        <property name="cellImage18" value="" />
        <property name="actionText18" value="" />
        <property name="cellText19" value="" />
        <property name="cellImage19" value="" />
        <property name="actionText19" value="" />
        <property name="cellText20" value="" />
        <property name="cellImage20" value="" />
        <property name="actionText20" value="" />
        <property name="cellText21" value="" />
        <property name="cellImage21" value="" />
        <property name="actionText21" value="" />
        <property name="cellText22" value="" />
        <property name="cellImage22" value="" />
        <property name="actionText22" value="" />
        <property name="cellText23" value="" />
        <property name="cellImage23" value="" />
        <property name="actionText23" value="" />
        <property name="cellText24" value="" />
        <property name="cellImage24" value="" />
        <property name="actionText24" value="" />
        <property name="cellText25" value="" />
        <property name="cellImage25" value="" />
        <property name="actionText25" value="" />
        <property name="cellText26" value="" />
        <property name="cellImage26" value="" />
        <property name="actionText26" value="" />
        <property name="cellText27" value="" />
        <property name="cellImage27" value="" />
        <property name="actionText27" value="" />
        <property name="cellText28" value="" />
        <property name="cellImage28" value="" />
        <property name="actionText28" value="" />
        <property name="cellText29" value="" />
        <property name="cellImage29" value="" />
        <property name="actionText29" value="" />
        <property name="cellText30" value="" />
        <property name="cellImage30" value="" />
        <property name="actionText30" value="" />
        <property name="cellText31" value="" />
        <property name="cellImage31" value="" />
        <property name="actionText31" value="" />
        <property name="cellText32" value="" />
        <property name="cellImage32" value="" />
        <property name="actionText32" value="" />
        <property name="cellText33" value="" />
        <property name="cellImage33" value="" />
        <property name="actionText33" value="" />
        <property name="cellText34" value="" />
        <property name="cellImage34" value="" />
        <property name="actionText34" value="" />
        <property name="cellText35" value="" />
        <property name="cellImage35" value="" />
        <property name="actionText35" value="" />
        <property name="cellText36" value="" />
        <property name="cellImage36" value="" />
        <property name="actionText36" value="" />
      </properties>
      <layout>
        <posX>334</posX>
        <posY>133</posY>
      </layout>
      <gui>
        <posX>225</posX>
        <posY>1488</posY>
        <width>1663</width>
        <height>5689</height>
      </gui>
    </component>
    <component id="TextDisplay.1" type_id="asterics.TextDisplay">
      <description>GUI component, which displays text.</description>
      <ports>
        <inputPort portTypeID="input">
          <properties />
        </inputPort>
      </ports>
      <properties>
        <property name="caption" value="" />
        <property name="default" value="Welcome to AsTeRICS !" />
        <property name="textPosition" value="1" />
        <property name="textColor" value="10" />
        <property name="backgroundColor" value="11" />
        <property name="displayGUI" value="true" />
      </properties>
      <layout>
        <posX>663</posX>
        <posY>135</posY>
      </layout>
      <gui>
        <posX>175</posX>
        <posY>1066</posY>
        <width>1750</width>
        <height>333</height>
      </gui>
    </component>
    <component id="TextArea.2" type_id="asterics.TextArea">
      <description>GUI component, which displays text.</description>
      <ports>
        <inputPort portTypeID="setText">
          <properties />
        </inputPort>
        <inputPort portTypeID="appendText">
          <properties />
        </inputPort>
        <outputPort portTypeID="text">
          <properties />
        </outputPort>
      </ports>
      <properties>
        <property name="caption" value="Selected Menu Entry" />
        <property name="default" value="" />
        <property name="editable" value="false" />
        <property name="fontSize" value="14" />
        <property name="textColor" value="0" />
        <property name="backgroundColor" value="11" />
        <property name="displayGUI" value="true" />
      </properties>
      <layout>
        <posX>692</posX>
        <posY>336</posY>
      </layout>
      <gui>
        <posX>2010</posX>
        <posY>3343</posY>
        <width>3000</width>
        <height>2000</height>
      </gui>
    </component>
    <component id="StringDispatcher.1" type_id="asterics.StringDispatcher">
      <description>Send test from chosen slot</description>
      <ports>
        <inputPort portTypeID="slotDispatch">
          <properties />
        </inputPort>
        <outputPort portTypeID="output">
          <properties />
        </outputPort>
      </ports>
      <properties>
        <property name="delay" value="300" />
        <property name="slot1" value="CameraMouse.acs" />
        <property name="slot2" value="OskaWriting.acs" />
        <property name="slot3" value="SpeechControl.acs" />
        <property name="slot4" value="GamepadMouse.acs" />
        <property name="slot5" value="ImageDemo.acs" />
        <property name="slot6" value="Ergotherapie/ergomenu.acs" />
        <property name="slot7" value="" />
        <property name="slot8" value="" />
        <property name="slot9" value="" />
        <property name="slot10" value="" />
        <property name="slot11" value="" />
        <property name="slot12" value="" />
        <property name="slot13" value="" />
        <property name="slot14" value="" />
        <property name="slot15" value="" />
        <property name="slot16" value="" />
        <property name="slot17" value="" />
        <property name="slot18" value="" />
        <property name="slot19" value="" />
        <property name="slot20" value="" />
      </properties>
      <layout>
        <posX>491</posX>
        <posY>127</posY>
      </layout>
    </component>
    <component id="TextDisplay.1.1" type_id="asterics.TextDisplay">
      <description>GUI component, which displays text.</description>
      <ports>
        <inputPort portTypeID="input">
          <properties />
        </inputPort>
      </ports>
      <properties>
        <property name="caption" value="" />
        <property name="default" value="choose or deploy a model" />
        <property name="textPosition" value="1" />
        <property name="textColor" value="10" />
        <property name="backgroundColor" value="11" />
        <property name="displayGUI" value="true" />
      </properties>
      <layout>
        <posX>304</posX>
        <posY>334</posY>
      </layout>
      <gui>
        <posX>188</posX>
        <posY>7266</posY>
        <width>1800</width>
        <height>333</height>
      </gui>
    </component>
    <component id="EmulateFaultyPlugin.1" type_id="asterics.EmulateFaultyPlugin">
      <description>Emulates a faulty plugin - supports throwing exceptions during method calls or hanging (unresponsive) method calls </description>
      <ports>
        <inputPort portTypeID="inA">
          <properties />
        </inputPort>
        <inputPort portTypeID="inB">
          <properties />
        </inputPort>
        <inputPort portTypeID="inC">
          <properties />
        </inputPort>
        <inputPort portTypeID="inD">
          <properties />
        </inputPort>
      </ports>
      <properties>
        <property name="startException" value="false" />
        <property name="pauseException" value="false" />
        <property name="resumeException" value="false" />
        <property name="stopException" value="false" />
        <property name="startDuration" value="0" />
        <property name="pauseDuration" value="0" />
        <property name="resumeDuration" value="0" />
        <property name="stopDuration" value="0" />
        <property name="inADuration" value="-1" />
        <property name="inBDuration" value="0" />
        <property name="inCDuration" value="0" />
        <property name="inDDuration" value="0" />
        <property name="eventADuration" value="0" />
        <property name="eventBDuration" value="0" />
        <property name="eventCDuration" value="0" />
      </properties>
      <layout>
        <posX>557</posX>
        <posY>348</posY>
      </layout>
      <gui>
        <posX>-7487</posX>
        <posY>888</posY>
        <width>30</width>
        <height>20</height>
      </gui>
    </component>
    <component id="TextArea.1" type_id="asterics.TextArea">
      <description>GUI component, which displays text.</description>
      <ports>
        <inputPort portTypeID="setText">
          <properties />
        </inputPort>
        <inputPort portTypeID="appendText">
          <properties />
        </inputPort>
        <outputPort portTypeID="text">
          <properties />
        </outputPort>
      </ports>
      <properties>
        <property name="caption" value="Help" />
        <property name="default" value="Click on any button! This triggers a dead lock in the model executor. The selection should not work but the GUI must not freeze. Try to set a CellBoard property, the action should fail but the ARE must not die. Finally try to stop the model. After a timeout the model should be stoppable and the ARE responsive." />
        <property name="editable" value="false" />
        <property name="fontSize" value="14" />
        <property name="textColor" value="0" />
        <property name="backgroundColor" value="11" />
        <property name="displayGUI" value="true" />
      </properties>
      <layout>
        <posX>52</posX>
        <posY>40</posY>
      </layout>
      <gui>
        <posX>2010</posX>
        <posY>1232</posY>
        <width>3000</width>
        <height>2000</height>
      </gui>
    </component>
  </components>
  <channels>
    <channel id="binding.2">
      <source>
        <component id="StringDispatcher.1" />
        <port id="output" />
      </source>
      <target>
        <component id="TextArea.2" />
        <port id="setText" />
      </target>
    </channel>
    <channel id="binding.1">
      <source>
        <component id="CellBoard.1" />
        <port id="selectedCell" />
      </source>
      <target>
        <component id="EmulateFaultyPlugin.1" />
        <port id="inA" />
      </target>
    </channel>
  </channels>
  <eventChannels>
    <eventChannel id="cell1_dispatchSlot1">
      <description />
      <sources>
        <source>
          <component id="CellBoard.1" />
          <eventPort id="cell1" />
        </source>
      </sources>
      <targets>
        <target>
          <component id="StringDispatcher.1" />
          <eventPort id="dispatchSlot1" />
        </target>
      </targets>
    </eventChannel>
    <eventChannel id="cell2_dispatchSlot2">
      <description />
      <sources>
        <source>
          <component id="CellBoard.1" />
          <eventPort id="cell2" />
        </source>
      </sources>
      <targets>
        <target>
          <component id="StringDispatcher.1" />
          <eventPort id="dispatchSlot2" />
        </target>
      </targets>
    </eventChannel>
    <eventChannel id="cell3_dispatchSlot3">
      <description />
      <sources>
        <source>
          <component id="CellBoard.1" />
          <eventPort id="cell3" />
        </source>
      </sources>
      <targets>
        <target>
          <component id="StringDispatcher.1" />
          <eventPort id="dispatchSlot3" />
        </target>
      </targets>
    </eventChannel>
    <eventChannel id="cell4_dispatchSlot4">
      <description />
      <sources>
        <source>
          <component id="CellBoard.1" />
          <eventPort id="cell4" />
        </source>
      </sources>
      <targets>
        <target>
          <component id="StringDispatcher.1" />
          <eventPort id="dispatchSlot4" />
        </target>
      </targets>
    </eventChannel>
    <eventChannel id="cell5_dispatchSlot5">
      <description />
      <sources>
        <source>
          <component id="CellBoard.1" />
          <eventPort id="cell5" />
        </source>
      </sources>
      <targets>
        <target>
          <component id="StringDispatcher.1" />
          <eventPort id="dispatchSlot5" />
        </target>
      </targets>
    </eventChannel>
    <eventChannel id="cell6_dispatchSlot6">
      <description />
      <sources>
        <source>
          <component id="CellBoard.1" />
          <eventPort id="cell6" />
        </source>
      </sources>
      <targets>
        <target>
          <component id="StringDispatcher.1" />
          <eventPort id="dispatchSlot6" />
        </target>
      </targets>
    </eventChannel>
  </eventChannels>
  <modelGUI>
    <Decoration>true</Decoration>
    <Fullscreen>false</Fullscreen>
    <AlwaysOnTop>false</AlwaysOnTop>
    <ToSystemTray>false</ToSystemTray>
    <ShopControlPanel>true</ShopControlPanel>
    <AREGUIWindow>
      <posX>175</posX>
      <posY>489</posY>
      <width>4875</width>
      <height>7444</height>
    </AREGUIWindow>
  </modelGUI>
</model>