<?xml version="1.0"?>
<model xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" modelName="D:\AsTeRICS\AsTeRICS\Tests\integrationTests\Model execution\SignalGeneratorHangWithDeadlock.acs_2015_3_2_18_35" version="20130320">
  <modelDescription>
    <shortDescription />
    <requirements />
    <description />
  </modelDescription>
  <components>
    <component id="SignalGenerator.1" type_id="asterics.SignalGenerator">
      <description>Signal Generator</description>
      <ports>
        <outputPort portTypeID="out">
          <properties />
        </outputPort>
      </ports>
      <properties>
        <property name="sendInterval" value="2" />
        <property name="waveForm" value="1" />
        <property name="frequency" value="2" />
        <property name="amplitude" value="100" />
        <property name="phaseShift" value="0" />
        <property name="offset" value="0" />
      </properties>
      <layout>
        <posX>39</posX>
        <posY>164</posY>
      </layout>
    </component>
    <component id="Oscilloscope.1" type_id="asterics.Oscilloscope">
      <description>Oscilloscope display for one signal channel</description>
      <ports>
        <inputPort portTypeID="in" sync="true">
          <properties />
        </inputPort>
      </ports>
      <properties>
        <property name="displayBuffer" value="3" />
        <property name="drawingMode" value="0" />
        <property name="displayMode" value="0" />
        <property name="drawingInterval" value="100" />
        <property name="min" value="-100" />
        <property name="max" value="100" />
        <property name="gridColor" value="0" />
        <property name="channelColor" value="10" />
        <property name="backgroundColor" value="11" />
        <property name="fontSize" value="14" />
        <property name="caption" value="oscilloscope" />
        <property name="displayGUI" value="true" />
      </properties>
      <layout>
        <posX>490</posX>
        <posY>111</posY>
      </layout>
      <gui>
        <posX>0</posX>
        <posY>444</posY>
        <width>6000</width>
        <height>3000</height>
      </gui>
    </component>
    <component id="EmulateFaultyPlugin.1" type_id="asterics.EmulateFaultyPlugin">
      <description>Emulates a faulty plugin - supports throwing exceptions during method calls or hanging (unresponsive) method calls </description>
      <ports>
        <inputPort portTypeID="inA">
          <properties />
        </inputPort>
        <inputPort portTypeID="inB">
          <properties />
        </inputPort>
        <inputPort portTypeID="inC">
          <properties />
        </inputPort>
        <inputPort portTypeID="inD">
          <properties />
        </inputPort>
      </ports>
      <properties>
        <property name="startException" value="false" />
        <property name="pauseException" value="false" />
        <property name="resumeException" value="false" />
        <property name="stopException" value="false" />
        <property name="getInputPortException" value="false" />
        <property name="getOutputPortException" value="false" />
        <property name="getRuntimePropertyValueException" value="false" />
        <property name="setRuntimePropertyValueException" value="false" />
        <property name="getEventListenerPortException" value="false" />
        <property name="getInputPortNullValue" value="false" />
        <property name="getOutputPortNullValue" value="false" />
        <property name="getRuntimePropertyNullValue" value="false" />
        <property name="getEventListenerPortNullValue" value="false" />
        <property name="startDuration" value="0" />
        <property name="pauseDuration" value="0" />
        <property name="resumeDuration" value="0" />
        <property name="stopDuration" value="0" />
        <property name="getRuntimePropertyDuration" value="0" />
        <property name="setRuntimePropertyDuration" value="0" />
        <property name="inADuration" value="0" />
        <property name="inBDuration" value="0" />
        <property name="inCDuration" value="0" />
        <property name="inDDuration" value="0" />
        <property name="eventADuration" value="-1" />
        <property name="eventBDuration" value="0" />
        <property name="eventCDuration" value="0" />
      </properties>
      <layout>
        <posX>265</posX>
        <posY>343</posY>
      </layout>
      <gui>
        <posX>0</posX>
        <posY>444</posY>
        <width>30</width>
        <height>20</height>
      </gui>
    </component>
    <component id="ButtonGrid.1" type_id="asterics.ButtonGrid">
      <description>Keyboard which sends event after button press</description>
      <ports />
      <properties>
        <property name="caption" value="Keyboard" />
        <property name="horizontalOrientation" value="false" />
        <property name="textColor" value="13" />
        <property name="backgroundColor" value="13" />
        <property name="borderColor" value="13" />
        <property name="borderThickness" value="2" />
        <property name="selectionFrameColor" value="13" />
        <property name="selectionFrameThickness" value="4" />
        <property name="displayGUI" value="true" />
        <property name="buttonCaption1" value="Start dead lock" />
        <property name="buttonCaption2" value="" />
        <property name="buttonCaption3" value="" />
        <property name="buttonCaption4" value="" />
        <property name="buttonCaption5" value="" />
        <property name="buttonCaption6" value="" />
        <property name="buttonCaption7" value="" />
        <property name="buttonCaption8" value="" />
        <property name="buttonCaption9" value="" />
        <property name="buttonCaption10" value="" />
        <property name="buttonCaption11" value="" />
        <property name="buttonCaption12" value="" />
        <property name="buttonCaption13" value="" />
        <property name="buttonCaption14" value="" />
        <property name="buttonCaption15" value="" />
        <property name="buttonCaption16" value="" />
        <property name="buttonCaption17" value="" />
        <property name="buttonCaption18" value="" />
        <property name="buttonCaption19" value="" />
        <property name="buttonCaption20" value="" />
        <property name="toolTip1" value="" />
        <property name="toolTip2" value="" />
        <property name="toolTip3" value="" />
        <property name="toolTip4" value="" />
        <property name="toolTip5" value="" />
        <property name="toolTip6" value="" />
        <property name="toolTip7" value="" />
        <property name="toolTip8" value="" />
        <property name="toolTip9" value="" />
        <property name="toolTip10" value="" />
        <property name="toolTip11" value="" />
        <property name="toolTip12" value="" />
        <property name="toolTip13" value="" />
        <property name="toolTip14" value="" />
        <property name="toolTip15" value="" />
        <property name="toolTip16" value="" />
        <property name="toolTip17" value="" />
        <property name="toolTip18" value="" />
        <property name="toolTip19" value="" />
        <property name="toolTip20" value="" />
      </properties>
      <layout>
        <posX>52</posX>
        <posY>358</posY>
      </layout>
      <gui>
        <posX>6135</posX>
        <posY>565</posY>
        <width>500</width>
        <height>2000</height>
      </gui>
    </component>
    <component id="Oscilloscope.2" type_id="asterics.Oscilloscope">
      <description>Oscilloscope display for one signal channel</description>
      <ports>
        <inputPort portTypeID="in" sync="true">
          <properties />
        </inputPort>
      </ports>
      <properties>
        <property name="displayBuffer" value="3" />
        <property name="drawingMode" value="0" />
        <property name="displayMode" value="0" />
        <property name="drawingInterval" value="100" />
        <property name="min" value="-100" />
        <property name="max" value="100" />
        <property name="gridColor" value="0" />
        <property name="channelColor" value="10" />
        <property name="backgroundColor" value="11" />
        <property name="fontSize" value="14" />
        <property name="caption" value="oscilloscope" />
        <property name="displayGUI" value="true" />
      </properties>
      <layout>
        <posX>499</posX>
        <posY>284</posY>
      </layout>
      <gui>
        <posX>10</posX>
        <posY>3565</posY>
        <width>6000</width>
        <height>3000</height>
      </gui>
    </component>
  </components>
  <channels>
    <channel id="binding.0">
      <description />
      <source>
        <component id="SignalGenerator.1" />
        <port id="out" />
      </source>
      <target>
        <component id="Oscilloscope.1" />
        <port id="in" />
      </target>
    </channel>
    <channel id="binding.1">
      <source>
        <component id="SignalGenerator.1" />
        <port id="out" />
      </source>
      <target>
        <component id="Oscilloscope.2" />
        <port id="in" />
      </target>
    </channel>
  </channels>
  <eventChannels>
    <eventChannel id="button1_eventA">
      <sources>
        <source>
          <component id="ButtonGrid.1" />
          <eventPort id="button1" />
        </source>
      </sources>
      <targets>
        <target>
          <component id="EmulateFaultyPlugin.1" />
          <eventPort id="eventA" />
        </target>
      </targets>
    </eventChannel>
  </eventChannels>
  <modelGUI>
    <Decoration>true</Decoration>
    <Fullscreen>false</Fullscreen>
    <AlwaysOnTop>false</AlwaysOnTop>
    <ToSystemTray>false</ToSystemTray>
    <ShopControlPanel>true</ShopControlPanel>
    <AREGUIWindow>
      <posX>0</posX>
      <posY>0</posY>
      <width>7188</width>
      <height>6778</height>
    </AREGUIWindow>
  </modelGUI>
</model>