<?xml version="1.0"?>
<model xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" modelName="D:\AsTeRICS\AsTeRICS_master\AsTeRICS\Tests\integrationTests\04_Model execution\TestSliderStorage.acs_2015_6_30_14_53" version="20130320">
  <components>
    <component id="Slider.1" type_id="asterics.Slider">
      <description>a slider GUI element which provides the slider value at an output port</description>
      <ports>
        <inputPort portTypeID="setValue">
          <properties />
        </inputPort>
        <inputPort portTypeID="in">
          <properties />
        </inputPort>
        <outputPort portTypeID="value">
          <properties />
        </outputPort>
        <outputPort portTypeID="out">
          <properties />
        </outputPort>
      </ports>
      <properties>
        <property name="min" value="0" />
        <property name="max" value="100" />
        <property name="default" value="50" />
        <property name="gain" value="0.01" />
        <property name="autosend" value="true" />
        <property name="caption" value="my slider" />
        <property name="majorTickSpacing" value="10" />
        <property name="minorTickSpacing" value="5" />
        <property name="alignment" value="0" />
        <property name="fontSize" value="14" />
        <property name="storeValue" value="True" />
        <property name="displayGUI" value="true" />
      </properties>
      <layout>
        <posX>40</posX>
        <posY>40</posY>
      </layout>
      <gui>
        <posX>72</posX>
        <posY>676</posY>
        <width>4000</width>
        <height>1000</height>
      </gui>
    </component>
  </components>
  <modelGUI>
    <Decoration>true</Decoration>
    <Fullscreen>false</Fullscreen>
    <AlwaysOnTop>false</AlwaysOnTop>
    <ToSystemTray>false</ToSystemTray>
    <ShopControlPanel>true</ShopControlPanel>
    <AREGUIWindow>
      <posX>0</posX>
      <posY>0</posY>
      <width>9000</width>
      <height>5000</height>
    </AREGUIWindow>
  </modelGUI>
</model>