<?xml version="1.0"?>
<model xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" modelName="D:\AsTeRICS\AsTeRICS_singleThreadedStabilization\AsTeRICS\Tests\integrationTests\Model execution\TimerMultipleEventsHangByButtonClick.acs_2015_3_3_20_59" version="20130320">
  <components>
    <component id="Timer.1" type_id="asterics.Timer">
      <description>measures and outputs time in milliseconds and fires events (periodically or once)</description>
      <ports>
        <inputPort portTypeID="period">
          <properties />
        </inputPort>
        <outputPort portTypeID="time">
          <properties />
        </outputPort>
      </ports>
      <properties>
        <property name="mode" value="1" />
        <property name="repeatCounter" value="5" />
        <property name="timePeriod" value="2000" />
        <property name="resolution" value="50" />
        <property name="waitPeriod" value="0" />
        <property name="autostart" value="True" />
      </properties>
      <layout>
        <posX>52</posX>
        <posY>127</posY>
      </layout>
    </component>
    <component id="EventVisualizer.1" type_id="asterics.EventVisualizer">
      <description>Simple Event Visualizer</description>
      <ports />
      <properties>
        <property name="displayGUI" value="true" />
      </properties>
      <layout>
        <posX>475</posX>
        <posY>87</posY>
      </layout>
      <gui>
        <posX>0</posX>
        <posY>444</posY>
        <width>3000</width>
        <height>1000</height>
      </gui>
    </component>
    <component id="EmulateFaultyPlugin.1" type_id="asterics.EmulateFaultyPlugin">
      <description>Emulates a faulty plugin - supports throwing exceptions during method calls or hanging (unresponsive) method calls </description>
      <ports>
        <inputPort portTypeID="inA">
          <properties />
        </inputPort>
        <inputPort portTypeID="inB">
          <properties />
        </inputPort>
        <inputPort portTypeID="inC">
          <properties />
        </inputPort>
        <inputPort portTypeID="inD">
          <properties />
        </inputPort>
      </ports>
      <properties>
        <property name="startException" value="false" />
        <property name="pauseException" value="false" />
        <property name="resumeException" value="false" />
        <property name="stopException" value="false" />
        <property name="getInputPortException" value="false" />
        <property name="getOutputPortException" value="false" />
        <property name="getRuntimePropertyValueException" value="false" />
        <property name="setRuntimePropertyValueException" value="false" />
        <property name="getEventListenerPortException" value="false" />
        <property name="getInputPortNullValue" value="false" />
        <property name="getOutputPortNullValue" value="false" />
        <property name="getRuntimePropertyNullValue" value="false" />
        <property name="getEventListenerPortNullValue" value="false" />
        <property name="startDuration" value="0" />
        <property name="pauseDuration" value="0" />
        <property name="resumeDuration" value="0" />
        <property name="stopDuration" value="0" />
        <property name="getRuntimePropertyDuration" value="0" />
        <property name="setRuntimePropertyDuration" value="0" />
        <property name="inADuration" value="-1" />
        <property name="inBDuration" value="0" />
        <property name="inCDuration" value="0" />
        <property name="inDDuration" value="0" />
        <property name="eventADuration" value="-1" />
        <property name="eventBDuration" value="0" />
        <property name="eventCDuration" value="0" />
      </properties>
      <layout>
        <posX>553</posX>
        <posY>284</posY>
      </layout>
      <gui>
        <posX>0</posX>
        <posY>444</posY>
        <width>30</width>
        <height>20</height>
      </gui>
    </component>
    <component id="ButtonGrid.1" type_id="asterics.ButtonGrid">
      <description>Keyboard which sends event after button press</description>
      <ports />
      <properties>
        <property name="caption" value="Keyboard" />
        <property name="horizontalOrientation" value="false" />
        <property name="textColor" value="13" />
        <property name="backgroundColor" value="13" />
        <property name="borderColor" value="13" />
        <property name="borderThickness" value="2" />
        <property name="selectionFrameColor" value="13" />
        <property name="selectionFrameThickness" value="4" />
        <property name="displayGUI" value="true" />
        <property name="buttonCaption1" value="Start Dead Lock" />
        <property name="buttonCaption2" value="" />
        <property name="buttonCaption3" value="" />
        <property name="buttonCaption4" value="" />
        <property name="buttonCaption5" value="" />
        <property name="buttonCaption6" value="" />
        <property name="buttonCaption7" value="" />
        <property name="buttonCaption8" value="" />
        <property name="buttonCaption9" value="" />
        <property name="buttonCaption10" value="" />
        <property name="buttonCaption11" value="" />
        <property name="buttonCaption12" value="" />
        <property name="buttonCaption13" value="" />
        <property name="buttonCaption14" value="" />
        <property name="buttonCaption15" value="" />
        <property name="buttonCaption16" value="" />
        <property name="buttonCaption17" value="" />
        <property name="buttonCaption18" value="" />
        <property name="buttonCaption19" value="" />
        <property name="buttonCaption20" value="" />
        <property name="toolTip1" value="" />
        <property name="toolTip2" value="" />
        <property name="toolTip3" value="" />
        <property name="toolTip4" value="" />
        <property name="toolTip5" value="" />
        <property name="toolTip6" value="" />
        <property name="toolTip7" value="" />
        <property name="toolTip8" value="" />
        <property name="toolTip9" value="" />
        <property name="toolTip10" value="" />
        <property name="toolTip11" value="" />
        <property name="toolTip12" value="" />
        <property name="toolTip13" value="" />
        <property name="toolTip14" value="" />
        <property name="toolTip15" value="" />
        <property name="toolTip16" value="" />
        <property name="toolTip17" value="" />
        <property name="toolTip18" value="" />
        <property name="toolTip19" value="" />
        <property name="toolTip20" value="" />
      </properties>
      <layout>
        <posX>73</posX>
        <posY>348</posY>
      </layout>
      <gui>
        <posX>0</posX>
        <posY>444</posY>
        <width>500</width>
        <height>2000</height>
      </gui>
    </component>
    <component id="EventFlipFlop.1" type_id="asterics.EventFlipFlop">
      <description>Event Flip-flop: First event-in fires event-out1, second event-in fires event-out2, etc.</description>
      <ports />
      <properties />
      <layout>
        <posX>260</posX>
        <posY>56</posY>
      </layout>
    </component>
  </components>
  <eventChannels>
    <eventChannel id="button1_eventA">
      <description />
      <sources>
        <source>
          <component id="ButtonGrid.1" />
          <eventPort id="button1" />
        </source>
      </sources>
      <targets>
        <target>
          <component id="EmulateFaultyPlugin.1" />
          <eventPort id="eventA" />
        </target>
      </targets>
    </eventChannel>
    <eventChannel id="periodFinished_event-in">
      <description />
      <sources>
        <source>
          <component id="Timer.1" />
          <eventPort id="periodFinished" />
        </source>
      </sources>
      <targets>
        <target>
          <component id="EventFlipFlop.1" />
          <eventPort id="event-in" />
        </target>
      </targets>
    </eventChannel>
    <eventChannel id="event-out1_eventDisplay">
      <description />
      <sources>
        <source>
          <component id="EventFlipFlop.1" />
          <eventPort id="event-out1" />
        </source>
      </sources>
      <targets>
        <target>
          <component id="EventVisualizer.1" />
          <eventPort id="eventDisplay" />
        </target>
      </targets>
    </eventChannel>
    <eventChannel id="event-out2_eventDisplay">
      <description />
      <sources>
        <source>
          <component id="EventFlipFlop.1" />
          <eventPort id="event-out2" />
        </source>
      </sources>
      <targets>
        <target>
          <component id="EventVisualizer.1" />
          <eventPort id="eventDisplay" />
        </target>
      </targets>
    </eventChannel>
  </eventChannels>
  <modelGUI>
    <Decoration>true</Decoration>
    <Fullscreen>false</Fullscreen>
    <AlwaysOnTop>false</AlwaysOnTop>
    <ToSystemTray>false</ToSystemTray>
    <ShopControlPanel>true</ShopControlPanel>
    <AREGUIWindow>
      <posX>0</posX>
      <posY>0</posY>
      <width>9000</width>
      <height>5000</height>
    </AREGUIWindow>
  </modelGUI>
</model>