/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class eu_asterics_component_sensor_spacenavigtor3Dmouse_SpaceNavigtor3DMouseBridge */

#ifndef _Included_eu_asterics_component_sensor_spacenavigtor3Dmouse_SpaceNavigtor3DMouseBridge
#define _Included_eu_asterics_component_sensor_spacenavigtor3Dmouse_SpaceNavigtor3DMouseBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     eu_asterics_component_sensor_spacenavigtor3Dmouse_SpaceNavigtor3DMouseBridge
 * Method:    activate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_eu_asterics_component_sensor_spacenavigtor3Dmouse_SpaceNavigtor3DMouseBridge_activate
  (JNIEnv *, jobject);

/*
 * Class:     eu_asterics_component_sensor_spacenavigtor3Dmouse_SpaceNavigtor3DMouseBridge
 * Method:    deactivate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_eu_asterics_component_sensor_spacenavigtor3Dmouse_SpaceNavigtor3DMouseBridge_deactivate
  (JNIEnv *, jobject);

/*
 * Class:     eu_asterics_component_sensor_spacenavigtor3Dmouse_SpaceNavigtor3DMouseBridge
 * Method:    getData
 * Signature: ([J)I
 */
JNIEXPORT jint JNICALL Java_eu_asterics_component_sensor_spacenavigtor3Dmouse_SpaceNavigtor3DMouseBridge_getData
  (JNIEnv *, jobject, jlongArray);

#ifdef __cplusplus
}
#endif
#endif
