Description of openFiles
openFiles
PURPOSE
SYNOPSIS
function [dataTrain,dataTest]=openFiles(dirPath,filePrefix)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
main_Asterics_Test1_wl_OVR_v1 matlab routine to go through the folders,
main_Asterics_Test2_wl_anova_OVR_v1 matlab routine to go through the folders,
main_TestDeciimationTPR112_v4_SoA matlab routine to go through the folders,
SOURCE CODE
function [dataTrain,dataTest]=openFiles(dirPath,filePrefix)
if nargin<1
    dirPath='Z:\UCONTROL-P20070527-01\BCI competition iii\OVR_aproach\features subject k3b\';
end
if nargin<2
    filePrefix='';
end
for i=1:4
    disp(i)
    filename=[dirPath,filePrefix,'features4aproach1_c',int2str(i)]
    load(filename)
    dataTrain(i)=data
    filename=[dirPath,filePrefix,'test_features4aproach1_c',int2str(i)]
    load(filename)
    dataTest(i)=data
end