/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class eu_asterics_component_sensor_intelrealsense_BridgeIntelRealSense */

#ifndef _Included_eu_asterics_component_sensor_intelrealsense_BridgeIntelRealSense
#define _Included_eu_asterics_component_sensor_intelrealsense_BridgeIntelRealSense
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     eu_asterics_component_sensor_intelrealsense_BridgeIntelRealSense
 * Method:    init
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_eu_asterics_component_sensor_intelrealsense_BridgeIntelRealSense_init
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     eu_asterics_component_sensor_intelrealsense_BridgeIntelRealSense
 * Method:    deactivate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_eu_asterics_component_sensor_intelrealsense_BridgeIntelRealSense_deactivate
  (JNIEnv *, jobject);

/*
 * Class:     eu_asterics_component_sensor_intelrealsense_BridgeIntelRealSense
 * Method:    startTracking
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_eu_asterics_component_sensor_intelrealsense_BridgeIntelRealSense_startTracking
  (JNIEnv *, jobject);

/*
* Class:     eu_asterics_component_sensor_intelrealsense_BridgeIntelRealSense
* Method:    pause
* Signature: ()V
*/
JNIEXPORT void JNICALL Java_eu_asterics_component_sensor_intelrealsense_BridgeIntelRealSense_pause
(JNIEnv *, jobject);

/*
* Class:     eu_asterics_component_sensor_intelrealsense_BridgeIntelRealSense
* Method:    resume
* Signature: ()V
*/
JNIEXPORT void JNICALL Java_eu_asterics_component_sensor_intelrealsense_BridgeIntelRealSense_resume
(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
