/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class eu_asterics_component_sensor_facetrackerCLM2_jni_FacetrackerCLM2Bridge */

#ifndef _Included_eu_asterics_component_sensor_facetrackerCLM2_jni_FacetrackerCLM2Bridge
#define _Included_eu_asterics_component_sensor_facetrackerCLM2_jni_FacetrackerCLM2Bridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     eu_asterics_component_sensor_facetrackerCLM2_jni_FacetrackerCLM2Bridge
 * Method:    activate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_eu_asterics_component_sensor_facetrackerCLM2_jni_FacetrackerCLM2Bridge_activate
  (JNIEnv *, jobject);

/*
 * Class:     eu_asterics_component_sensor_facetrackerCLM2_jni_FacetrackerCLM2Bridge
 * Method:    suspend
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_eu_asterics_component_sensor_facetrackerCLM2_jni_FacetrackerCLM2Bridge_suspend
  (JNIEnv *, jobject);

/*
 * Class:     eu_asterics_component_sensor_facetrackerCLM2_jni_FacetrackerCLM2Bridge
 * Method:    resume
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_eu_asterics_component_sensor_facetrackerCLM2_jni_FacetrackerCLM2Bridge_resume
  (JNIEnv *, jobject);

/*
 * Class:     eu_asterics_component_sensor_facetrackerCLM2_jni_FacetrackerCLM2Bridge
 * Method:    deactivate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_eu_asterics_component_sensor_facetrackerCLM2_jni_FacetrackerCLM2Bridge_deactivate
  (JNIEnv *, jobject);

/*
 * Class:     eu_asterics_component_sensor_facetrackerCLM2_jni_FacetrackerCLM2Bridge
 * Method:    showCameraSettings
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_eu_asterics_component_sensor_facetrackerCLM2_jni_FacetrackerCLM2Bridge_showCameraSettings
  (JNIEnv *, jobject);

/*
 * Class:     eu_asterics_component_sensor_facetrackerCLM2_jni_FacetrackerCLM2Bridge
 * Method:    setReferencePose
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_eu_asterics_component_sensor_facetrackerCLM2_jni_FacetrackerCLM2Bridge_setReferencePose
  (JNIEnv *, jobject);

/*
 * Class:     eu_asterics_component_sensor_facetrackerCLM2_jni_FacetrackerCLM2Bridge
 * Method:    setDisplayPosition
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_eu_asterics_component_sensor_facetrackerCLM2_jni_FacetrackerCLM2Bridge_setDisplayPosition
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     eu_asterics_component_sensor_facetrackerCLM2_jni_FacetrackerCLM2Bridge
 * Method:    getProperty
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_eu_asterics_component_sensor_facetrackerCLM2_jni_FacetrackerCLM2Bridge_getProperty
  (JNIEnv *, jobject, jstring);

/*
 * Class:     eu_asterics_component_sensor_facetrackerCLM2_jni_FacetrackerCLM2Bridge
 * Method:    setProperty
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_eu_asterics_component_sensor_facetrackerCLM2_jni_FacetrackerCLM2Bridge_setProperty
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     eu_asterics_component_sensor_facetrackerCLM2_jni_FacetrackerCLM2Bridge
 * Method:    reset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_eu_asterics_component_sensor_facetrackerCLM2_jni_FacetrackerCLM2Bridge_reset
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
