/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class eu_asterics_component_actuator_phonecontrol_PhoneControlBridge */

#ifndef _Included_eu_asterics_component_actuator_phonecontrol_PhoneControlBridge
#define _Included_eu_asterics_component_actuator_phonecontrol_PhoneControlBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     eu_asterics_component_actuator_phonecontrol_PhoneControlBridge
 * Method:    activate
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_eu_asterics_component_actuator_phonecontrol_PhoneControlBridge_activate
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     eu_asterics_component_actuator_phonecontrol_PhoneControlBridge
 * Method:    reconnectPhone
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_eu_asterics_component_actuator_phonecontrol_PhoneControlBridge_reconnectPhone
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     eu_asterics_component_actuator_phonecontrol_PhoneControlBridge
 * Method:    deactivate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_eu_asterics_component_actuator_phonecontrol_PhoneControlBridge_deactivate
  (JNIEnv *, jobject);

/*
 * Class:     eu_asterics_component_actuator_phonecontrol_PhoneControlBridge
 * Method:    acceptCall
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_eu_asterics_component_actuator_phonecontrol_PhoneControlBridge_acceptCall
  (JNIEnv *, jobject);

/*
 * Class:     eu_asterics_component_actuator_phonecontrol_PhoneControlBridge
 * Method:    dropCall
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_eu_asterics_component_actuator_phonecontrol_PhoneControlBridge_dropCall
  (JNIEnv *, jobject);

/*
 * Class:     eu_asterics_component_actuator_phonecontrol_PhoneControlBridge
 * Method:    makePhoneCall
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_eu_asterics_component_actuator_phonecontrol_PhoneControlBridge_makePhoneCall
  (JNIEnv *, jobject, jstring);

/*
 * Class:     eu_asterics_component_actuator_phonecontrol_PhoneControlBridge
 * Method:    sendSMS
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_eu_asterics_component_actuator_phonecontrol_PhoneControlBridge_sendSMS
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
