
/*
 *    AsTeRICS - Assistive Technology Rapid Integration and Construction Set
 * 
 * 
 *        d8888      88888888888       8888888b.  8888888 .d8888b.   .d8888b. 
 *       d88888          888           888   Y88b   888  d88P  Y88b d88P  Y88b
 *      d88P888          888           888    888   888  888    888 Y88b.     
 *     d88P 888 .d8888b  888   .d88b.  888   d88P   888  888         "Y888b.  
 *    d88P  888 88K      888  d8P  Y8b 8888888P"    888  888            "Y88b.
 *   d88P   888 "Y8888b. 888  88888888 888 T88b     888  888    888       "888
 *  d8888888888      X88 888  Y8b.     888  T88b    888  Y88b  d88P Y88b  d88P
 * d88P     888  88888P' 888   "Y8888  888   T88b 8888888 "Y8888P"   "Y8888P" 
 *
 *
 *                    homepage: http://www.asterics.org 
 *
 *     This project has been partly funded by the European Commission, 
 *                      Grant Agreement Number 247730
 *  
 *  
 *         Dual License: MIT or GPL v3.0 with "CLASSPATH" exception
 *         (please refer to the folder LICENSE)
 * 
 */


/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class eu_asterics_mw_component_actuator_MouseCursorIcon */

#ifndef _Included_eu_asterics_component_actuator_MouseCursorIcon
#define _Included_eu_asterics_component_actuator_MouseCursorIcon
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     eu_asterics_mw_component_actuator_MouseCursorIcon
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_eu_asterics_component_actuator_mousecursoricon_MouseCursorIconInstance_initCursor
  (JNIEnv *, jobject);


/*
 * Class:     eu_asterics_mw_component_actuator_MouseCursorIcon
 * Method:    setCursor
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_eu_asterics_component_actuator_mousecursoricon_MouseCursorIconInstance_setCursor
  (JNIEnv *, jobject, jstring);


/*
 * Class:     eu_asterics_mw_component_actuator_MouseCursorIcon
 * Method:    exit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_eu_asterics_component_actuator_mousecursoricon_MouseCursorIconInstance_exitCursor
  (JNIEnv *, jobject);


#ifdef __cplusplus
}
#endif
#endif
