<?xml version="1.0"?>
<model xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" modelName="D:\AsTeRICS\AsTeRICS\bin\ACS\models\integrationTests\Model data propagation\CSV\csvwriter.acs_2015_2_27_17_10" version="20130320">
  <components>
    <component id="WriteCSV.1" type_id="asterics.WriteCSV">
      <description>Write a csv file</description>
      <ports>
        <inputPort portTypeID="Input">
          <properties />
        </inputPort>
      </ports>
      <properties>
        <property name="FileName" value="fileName" />
        <property name="FilePath" value="data" />
      </properties>
      <layout>
        <posX>673</posX>
        <posY>174</posY>
      </layout>
    </component>
    <component id="SignalGenerator.1.1" type_id="asterics.SignalGenerator">
      <description>Signal Generator</description>
      <ports>
        <outputPort portTypeID="out">
          <properties />
        </outputPort>
      </ports>
      <properties>
        <property name="sendInterval" value="5" />
        <property name="waveForm" value="2" />
        <property name="frequency" value="1" />
        <property name="amplitude" value="100" />
        <property name="phaseShift" value="0" />
        <property name="offset" value="0" />
      </properties>
      <layout>
        <posX>32</posX>
        <posY>375</posY>
      </layout>
    </component>
    <component id="SignalGenerator.1" type_id="asterics.SignalGenerator">
      <description>Signal Generator</description>
      <ports>
        <outputPort portTypeID="out">
          <properties />
        </outputPort>
      </ports>
      <properties>
        <property name="sendInterval" value="5" />
        <property name="waveForm" value="1" />
        <property name="frequency" value="1" />
        <property name="amplitude" value="100" />
        <property name="phaseShift" value="0" />
        <property name="offset" value="0" />
      </properties>
      <layout>
        <posX>36</posX>
        <posY>236</posY>
      </layout>
    </component>
    <component id="DoubleToString.1" type_id="asterics.DoubleToString">
      <description>Converts double to string</description>
      <ports>
        <inputPort portTypeID="input">
          <properties />
        </inputPort>
        <outputPort portTypeID="output">
          <properties />
        </outputPort>
      </ports>
      <properties />
      <layout>
        <posX>157</posX>
        <posY>235</posY>
      </layout>
    </component>
    <component id="DoubleToString.1.1" type_id="asterics.DoubleToString">
      <description>Converts double to string</description>
      <ports>
        <inputPort portTypeID="input">
          <properties />
        </inputPort>
        <outputPort portTypeID="output">
          <properties />
        </outputPort>
      </ports>
      <properties />
      <layout>
        <posX>169</posX>
        <posY>380</posY>
      </layout>
    </component>
    <component id="ButtonGrid.1" type_id="asterics.ButtonGrid">
      <description>Keyboard which sends event after button press</description>
      <ports />
      <properties>
        <property name="caption" value="Keyboard" />
        <property name="horizontalOrientation" value="false" />
        <property name="textColor" value="13" />
        <property name="backgroundColor" value="13" />
        <property name="borderColor" value="13" />
        <property name="borderThickness" value="2" />
        <property name="selectionFrameColor" value="13" />
        <property name="selectionFrameThickness" value="4" />
        <property name="displayGUI" value="true" />
        <property name="buttonCaption1" value="Start Writing" />
        <property name="buttonCaption2" value="Stop Writing" />
        <property name="buttonCaption3" value="" />
        <property name="buttonCaption4" value="" />
        <property name="buttonCaption5" value="" />
        <property name="buttonCaption6" value="" />
        <property name="buttonCaption7" value="" />
        <property name="buttonCaption8" value="" />
        <property name="buttonCaption9" value="" />
        <property name="buttonCaption10" value="" />
        <property name="buttonCaption11" value="" />
        <property name="buttonCaption12" value="" />
        <property name="buttonCaption13" value="" />
        <property name="buttonCaption14" value="" />
        <property name="buttonCaption15" value="" />
        <property name="buttonCaption16" value="" />
        <property name="buttonCaption17" value="" />
        <property name="buttonCaption18" value="" />
        <property name="buttonCaption19" value="" />
        <property name="buttonCaption20" value="" />
        <property name="toolTip1" value="" />
        <property name="toolTip2" value="" />
        <property name="toolTip3" value="" />
        <property name="toolTip4" value="" />
        <property name="toolTip5" value="" />
        <property name="toolTip6" value="" />
        <property name="toolTip7" value="" />
        <property name="toolTip8" value="" />
        <property name="toolTip9" value="" />
        <property name="toolTip10" value="" />
        <property name="toolTip11" value="" />
        <property name="toolTip12" value="" />
        <property name="toolTip13" value="" />
        <property name="toolTip14" value="" />
        <property name="toolTip15" value="" />
        <property name="toolTip16" value="" />
        <property name="toolTip17" value="" />
        <property name="toolTip18" value="" />
        <property name="toolTip19" value="" />
        <property name="toolTip20" value="" />
      </properties>
      <layout>
        <posX>459</posX>
        <posY>399</posY>
      </layout>
      <gui>
        <posX>0</posX>
        <posY>466</posY>
        <width>500</width>
        <height>2000</height>
      </gui>
    </component>
    <component id="StringExpander.1" type_id="asterics.StringExpander">
      <description>Adds the preString and postString strings to the incoming string and sends the new string to the output port.</description>
      <ports>
        <inputPort portTypeID="input" sync="true">
          <properties />
        </inputPort>
        <inputPort portTypeID="preString" sync="true">
          <properties />
        </inputPort>
        <inputPort portTypeID="postString" sync="true">
          <properties />
        </inputPort>
        <outputPort portTypeID="output">
          <properties />
        </outputPort>
      </ports>
      <properties>
        <property name="preString" value="" />
        <property name="postString" value="" />
        <property name="trim" value="True" />
      </properties>
      <layout>
        <posX>444</posX>
        <posY>145</posY>
      </layout>
    </component>
    <component id="Timer.1" type_id="asterics.Timer">
      <description>measures and outputs time in milliseconds and fires events (periodically or once)</description>
      <ports>
        <inputPort portTypeID="period">
          <properties />
        </inputPort>
        <outputPort portTypeID="time">
          <properties />
        </outputPort>
      </ports>
      <properties>
        <property name="mode" value="2" />
        <property name="repeatCounter" value="1" />
        <property name="timePeriod" value="5" />
        <property name="resolution" value="50" />
        <property name="waitPeriod" value="0" />
        <property name="autostart" value="True" />
      </properties>
      <layout>
        <posX>99</posX>
        <posY>38</posY>
      </layout>
    </component>
    <component id="TextSender.1" type_id="asterics.TextSender">
      <description>Send text when gets event</description>
      <ports>
        <inputPort portTypeID="setText">
          <properties />
        </inputPort>
        <outputPort portTypeID="output">
          <properties />
        </outputPort>
      </ports>
      <properties>
        <property name="text" value=";" />
      </properties>
      <layout>
        <posX>252</posX>
        <posY>30</posY>
      </layout>
    </component>
    <component id="Oscilloscope.1" type_id="asterics.Oscilloscope">
      <description>Oscilloscope display for one signal channel</description>
      <ports>
        <inputPort portTypeID="in">
          <properties />
        </inputPort>
      </ports>
      <properties>
        <property name="displayBuffer" value="3" />
        <property name="drawingMode" value="0" />
        <property name="displayMode" value="0" />
        <property name="drawingInterval" value="100" />
        <property name="min" value="-100" />
        <property name="max" value="100" />
        <property name="gridColor" value="0" />
        <property name="channelColor" value="10" />
        <property name="backgroundColor" value="11" />
        <property name="fontSize" value="14" />
        <property name="caption" value="oscilloscope" />
        <property name="displayGUI" value="true" />
      </properties>
      <layout>
        <posX>239</posX>
        <posY>709</posY>
      </layout>
      <gui>
        <posX>10</posX>
        <posY>2454</posY>
        <width>6000</width>
        <height>3000</height>
      </gui>
    </component>
  </components>
  <channels>
    <channel id="binding.3">
      <source>
        <component id="SignalGenerator.1" />
        <port id="out" />
      </source>
      <target>
        <component id="DoubleToString.1" />
        <port id="input" />
      </target>
    </channel>
    <channel id="binding.2">
      <source>
        <component id="SignalGenerator.1.1" />
        <port id="out" />
      </source>
      <target>
        <component id="DoubleToString.1.1" />
        <port id="input" />
      </target>
    </channel>
    <channel id="binding.5">
      <source>
        <component id="DoubleToString.1" />
        <port id="output" />
      </source>
      <target>
        <component id="StringExpander.1" />
        <port id="preString" />
      </target>
    </channel>
    <channel id="binding.6">
      <source>
        <component id="DoubleToString.1.1" />
        <port id="output" />
      </source>
      <target>
        <component id="StringExpander.1" />
        <port id="postString" />
      </target>
    </channel>
    <channel id="binding.7">
      <source>
        <component id="StringExpander.1" />
        <port id="output" />
      </source>
      <target>
        <component id="WriteCSV.1" />
        <port id="Input" />
      </target>
    </channel>
    <channel id="binding.4">
      <source>
        <component id="TextSender.1" />
        <port id="output" />
      </source>
      <target>
        <component id="StringExpander.1" />
        <port id="input" />
      </target>
    </channel>
    <channel id="binding.8">
      <source>
        <component id="SignalGenerator.1" />
        <port id="out" />
      </source>
      <target>
        <component id="Oscilloscope.1" />
        <port id="in" />
      </target>
    </channel>
  </channels>
  <eventChannels>
    <eventChannel id="button1_StartWriting">
      <description />
      <sources>
        <source>
          <component id="ButtonGrid.1" />
          <eventPort id="button1" />
        </source>
      </sources>
      <targets>
        <target>
          <component id="WriteCSV.1" />
          <eventPort id="StartWriting" />
        </target>
      </targets>
    </eventChannel>
    <eventChannel id="button2_StopWriting">
      <description />
      <sources>
        <source>
          <component id="ButtonGrid.1" />
          <eventPort id="button2" />
        </source>
      </sources>
      <targets>
        <target>
          <component id="WriteCSV.1" />
          <eventPort id="StopWriting" />
        </target>
      </targets>
    </eventChannel>
    <eventChannel id="periodFinished_sendText">
      <description />
      <sources>
        <source>
          <component id="Timer.1" />
          <eventPort id="periodFinished" />
        </source>
      </sources>
      <targets>
        <target>
          <component id="TextSender.1" />
          <eventPort id="sendText" />
        </target>
      </targets>
    </eventChannel>
  </eventChannels>
  <modelGUI>
    <Decoration>true</Decoration>
    <Fullscreen>false</Fullscreen>
    <AlwaysOnTop>false</AlwaysOnTop>
    <ToSystemTray>false</ToSystemTray>
    <ShopControlPanel>true</ShopControlPanel>
    <AREGUIWindow>
      <posX>0</posX>
      <posY>22</posY>
      <width>9000</width>
      <height>9333</height>
    </AREGUIWindow>
  </modelGUI>
</model>