<?xml version="1.0"?>
<model xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" modelName="18.03.2015_754" version="20130320">
  <components>
    <component id="Arduino.1" type_id="asterics.Arduino">
      <description>Arduino Microcontroller CIM</description>
      <ports>
        <inputPort portTypeID="pwm3">
          <properties />
        </inputPort>
        <inputPort portTypeID="pwm5">
          <properties />
        </inputPort>
        <inputPort portTypeID="pwm6">
          <properties />
        </inputPort>
        <outputPort portTypeID="A0">
          <properties />
        </outputPort>
        <outputPort portTypeID="A1">
          <properties />
        </outputPort>
        <outputPort portTypeID="A2">
          <properties />
        </outputPort>
        <outputPort portTypeID="A3">
          <properties />
        </outputPort>
        <outputPort portTypeID="A4">
          <properties />
        </outputPort>
        <outputPort portTypeID="A5">
          <properties />
        </outputPort>
      </ports>
      <properties>
        <property name="periodicADCUpdate" value="200" />
        <property name="pin2Mode" value="0" />
        <property name="pin3Mode" value="0" />
        <property name="pin4Mode" value="0" />
        <property name="pin5Mode" value="0" />
        <property name="pin6Mode" value="0" />
        <property name="pin7Mode" value="0" />
        <property name="pin8Mode" value="0" />
        <property name="pin9Mode" value="0" />
        <property name="pin10Mode" value="0" />
        <property name="pin11Mode" value="0" />
        <property name="pin12Mode" value="0" />
        <property name="pin13Mode" value="0" />
      </properties>
      <layout>
        <posX>208</posX>
        <posY>158</posY>
      </layout>
    </component>
  </components>
  <modelGUI>
    <Decoration>true</Decoration>
    <Fullscreen>false</Fullscreen>
    <AlwaysOnTop>false</AlwaysOnTop>
    <ToSystemTray>false</ToSystemTray>
    <ShopControlPanel>true</ShopControlPanel>
    <AREGUIWindow>
      <posX>0</posX>
      <posY>0</posY>
      <width>9000</width>
      <height>5000</height>
    </AREGUIWindow>
  </modelGUI>
</model>