/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class eu_asterics_component_sensor_eyetracker_jni_BridgePOSIT */

#ifndef _Included_eu_asterics_component_sensor_eyetracker_jni_BridgePOSIT
#define _Included_eu_asterics_component_sensor_eyetracker_jni_BridgePOSIT
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     eu_asterics_component_sensor_eyetracker_jni_BridgePOSIT
 * Method:    activate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_eu_asterics_component_sensor_eyetracker_jni_BridgePOSIT_activate
  (JNIEnv *, jobject);

/*
 * Class:     eu_asterics_component_sensor_eyetracker_jni_BridgePOSIT
 * Method:    deactivate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_eu_asterics_component_sensor_eyetracker_jni_BridgePOSIT_deactivate
  (JNIEnv *, jobject);

/*
 * Class:     eu_asterics_component_sensor_eyetracker_jni_BridgePOSIT
 * Method:    runPOSIT
 * Signature: (IIIIIIII)I
 */
JNIEXPORT jint JNICALL Java_eu_asterics_component_sensor_eyetracker_jni_BridgePOSIT_runPOSIT
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     eu_asterics_component_sensor_eyetracker_jni_BridgePOSIT
 * Method:    togglePoseInfoWindow
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_eu_asterics_component_sensor_eyetracker_jni_BridgePOSIT_togglePoseInfoWindow
  (JNIEnv *, jobject);

/*
 * Class:     eu_asterics_component_sensor_eyetracker_jni_BridgePOSIT
 * Method:    startEval
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_eu_asterics_component_sensor_eyetracker_jni_BridgePOSIT_startEval
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     eu_asterics_component_sensor_eyetracker_jni_BridgePOSIT
 * Method:    sendEvalParams
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_eu_asterics_component_sensor_eyetracker_jni_BridgePOSIT_sendEvalParams
  (JNIEnv *, jobject, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
