package eu.asterics.mw.are.asapi;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/*
 *    AsTeRICS - Assistive Technology Rapid Integration and Construction Set
 *
 *
 *        d8888      88888888888       8888888b.  8888888 .d8888b.   .d8888b.
 *       d88888          888           888   Y88b   888  d88P  Y88b d88P  Y88b
 *      d88P888          888           888    888   888  888    888 Y88b.    
 *     d88P 888 .d8888b  888   .d88b.  888   d88P   888  888         "Y888b. 
 *    d88P  888 88K      888  d8P  Y8b 8888888P"    888  888            "Y88b.
 *   d88P   888 "Y8888b. 888  88888888 888 T88b     888  888    888       "888
 *  d8888888888      X88 888  Y8b.     888  T88b    888  Y88b  d88P Y88b  d88P
 * d88P     888  88888P' 888   "Y8888  888   T88b 8888888 "Y8888P"   "Y8888P"
 *
 *
 *                    homepage: http://www.asterics.org
 *
 *     This project has been partly funded by the European Commission,
 *                      Grant Agreement Number 247730
 * 
 * 
 *    License: GPL v3.0 (GNU General Public License Version 3.0)
 *                 http://www.gnu.org/licenses/gpl.html
 *
 */


/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */


public class AsapiException extends Exception implements org.apache.thrift.TBase<AsapiException, AsapiException._Fields>, java.io.Serializable, Cloneable {
	  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("AsapiException");

	  private static final org.apache.thrift.protocol.TField NUMBER_FIELD_DESC = new org.apache.thrift.protocol.TField("number", org.apache.thrift.protocol.TType.I32, (short)1);
	  private static final org.apache.thrift.protocol.TField DESCRIPTION_FIELD_DESC = new org.apache.thrift.protocol.TField("description", org.apache.thrift.protocol.TType.STRING, (short)2);

	  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
	  static {
	    schemes.put(StandardScheme.class, new AsapiExceptionStandardSchemeFactory());
	    schemes.put(TupleScheme.class, new AsapiExceptionTupleSchemeFactory());
	  }

	  public int number; // required
	  public String description; // required

	  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
	  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
	    NUMBER((short)1, "number"),
	    DESCRIPTION((short)2, "description");

	    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

	    static {
	      for (_Fields field : EnumSet.allOf(_Fields.class)) {
	        byName.put(field.getFieldName(), field);
	      }
	    }

	    /**
	     * Find the _Fields constant that matches fieldId, or null if its not found.
	     */
	    public static _Fields findByThriftId(int fieldId) {
	      switch(fieldId) {
	        case 1: // NUMBER
	          return NUMBER;
	        case 2: // DESCRIPTION
	          return DESCRIPTION;
	        default:
	          return null;
	      }
	    }

	    /**
	     * Find the _Fields constant that matches fieldId, throwing an exception
	     * if it is not found.
	     */
	    public static _Fields findByThriftIdOrThrow(int fieldId) {
	      _Fields fields = findByThriftId(fieldId);
	      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
	      return fields;
	    }

	    /**
	     * Find the _Fields constant that matches name, or null if its not found.
	     */
	    public static _Fields findByName(String name) {
	      return byName.get(name);
	    }

	    private final short _thriftId;
	    private final String _fieldName;

	    _Fields(short thriftId, String fieldName) {
	      _thriftId = thriftId;
	      _fieldName = fieldName;
	    }

	    public short getThriftFieldId() {
	      return _thriftId;
	    }

	    public String getFieldName() {
	      return _fieldName;
	    }
	  }

	  // isset id assignments
	  private static final int __NUMBER_ISSET_ID = 0;
	  private BitSet __isset_bit_vector = new BitSet(1);
	  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
	  static {
	    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
	    tmpMap.put(_Fields.NUMBER, new org.apache.thrift.meta_data.FieldMetaData("number", org.apache.thrift.TFieldRequirementType.DEFAULT, 
	        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
	    tmpMap.put(_Fields.DESCRIPTION, new org.apache.thrift.meta_data.FieldMetaData("description", org.apache.thrift.TFieldRequirementType.DEFAULT, 
	        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
	    metaDataMap = Collections.unmodifiableMap(tmpMap);
	    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(AsapiException.class, metaDataMap);
	  }

	  public AsapiException() {
	  }

	  public AsapiException(
	    int number,
	    String description)
	  {
	    this();
	    this.number = number;
	    setNumberIsSet(true);
	    this.description = description;
	  }

	  /**
	   * Performs a deep copy on <i>other</i>.
	   */
	  public AsapiException(AsapiException other) {
	    __isset_bit_vector.clear();
	    __isset_bit_vector.or(other.__isset_bit_vector);
	    this.number = other.number;
	    if (other.isSetDescription()) {
	      this.description = other.description;
	    }
	  }

	  public AsapiException deepCopy() {
	    return new AsapiException(this);
	  }

	  @Override
	  public void clear() {
	    setNumberIsSet(false);
	    this.number = 0;
	    this.description = null;
	  }

	  public int getNumber() {
	    return this.number;
	  }

	  public AsapiException setNumber(int number) {
	    this.number = number;
	    setNumberIsSet(true);
	    return this;
	  }

	  public void unsetNumber() {
	    __isset_bit_vector.clear(__NUMBER_ISSET_ID);
	  }

	  /** Returns true if field number is set (has been assigned a value) and false otherwise */
	  public boolean isSetNumber() {
	    return __isset_bit_vector.get(__NUMBER_ISSET_ID);
	  }

	  public void setNumberIsSet(boolean value) {
	    __isset_bit_vector.set(__NUMBER_ISSET_ID, value);
	  }

	  public String getDescription() {
	    return this.description;
	  }

	  public AsapiException setDescription(String description) {
	    this.description = description;
	    return this;
	  }

	  public void unsetDescription() {
	    this.description = null;
	  }

	  /** Returns true if field description is set (has been assigned a value) and false otherwise */
	  public boolean isSetDescription() {
	    return this.description != null;
	  }

	  public void setDescriptionIsSet(boolean value) {
	    if (!value) {
	      this.description = null;
	    }
	  }

	  public void setFieldValue(_Fields field, Object value) {
	    switch (field) {
	    case NUMBER:
	      if (value == null) {
	        unsetNumber();
	      } else {
	        setNumber((Integer)value);
	      }
	      break;

	    case DESCRIPTION:
	      if (value == null) {
	        unsetDescription();
	      } else {
	        setDescription((String)value);
	      }
	      break;

	    }
	  }

	  public Object getFieldValue(_Fields field) {
	    switch (field) {
	    case NUMBER:
	      return Integer.valueOf(getNumber());

	    case DESCRIPTION:
	      return getDescription();

	    }
	    throw new IllegalStateException();
	  }

	  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
	  public boolean isSet(_Fields field) {
	    if (field == null) {
	      throw new IllegalArgumentException();
	    }

	    switch (field) {
	    case NUMBER:
	      return isSetNumber();
	    case DESCRIPTION:
	      return isSetDescription();
	    }
	    throw new IllegalStateException();
	  }

	  @Override
	  public boolean equals(Object that) {
	    if (that == null)
	      return false;
	    if (that instanceof AsapiException)
	      return this.equals((AsapiException)that);
	    return false;
	  }

	  public boolean equals(AsapiException that) {
	    if (that == null)
	      return false;

	    boolean this_present_number = true;
	    boolean that_present_number = true;
	    if (this_present_number || that_present_number) {
	      if (!(this_present_number && that_present_number))
	        return false;
	      if (this.number != that.number)
	        return false;
	    }

	    boolean this_present_description = true && this.isSetDescription();
	    boolean that_present_description = true && that.isSetDescription();
	    if (this_present_description || that_present_description) {
	      if (!(this_present_description && that_present_description))
	        return false;
	      if (!this.description.equals(that.description))
	        return false;
	    }

	    return true;
	  }

	  @Override
	  public int hashCode() {
	    return 0;
	  }

	  public int compareTo(AsapiException other) {
	    if (!getClass().equals(other.getClass())) {
	      return getClass().getName().compareTo(other.getClass().getName());
	    }

	    int lastComparison = 0;
	    AsapiException typedOther = (AsapiException)other;

	    lastComparison = Boolean.valueOf(isSetNumber()).compareTo(typedOther.isSetNumber());
	    if (lastComparison != 0) {
	      return lastComparison;
	    }
	    if (isSetNumber()) {
	      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.number, typedOther.number);
	      if (lastComparison != 0) {
	        return lastComparison;
	      }
	    }
	    lastComparison = Boolean.valueOf(isSetDescription()).compareTo(typedOther.isSetDescription());
	    if (lastComparison != 0) {
	      return lastComparison;
	    }
	    if (isSetDescription()) {
	      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.description, typedOther.description);
	      if (lastComparison != 0) {
	        return lastComparison;
	      }
	    }
	    return 0;
	  }

	  public _Fields fieldForId(int fieldId) {
	    return _Fields.findByThriftId(fieldId);
	  }

	  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
	    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
	  }

	  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
	    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
	  }

	  @Override
	  public String toString() {
	    StringBuilder sb = new StringBuilder("AsapiException(");
	    boolean first = true;

	    sb.append("number:");
	    sb.append(this.number);
	    first = false;
	    if (!first) sb.append(", ");
	    sb.append("description:");
	    if (this.description == null) {
	      sb.append("null");
	    } else {
	      sb.append(this.description);
	    }
	    first = false;
	    sb.append(")");
	    return sb.toString();
	  }

	  public void validate() throws org.apache.thrift.TException {
	    // check for required fields
	  }

	  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
	    try {
	      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
	    } catch (org.apache.thrift.TException te) {
	      throw new java.io.IOException(te);
	    }
	  }

	  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
	    try {
	      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
	      __isset_bit_vector = new BitSet(1);
	      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
	    } catch (org.apache.thrift.TException te) {
	      throw new java.io.IOException(te);
	    }
	  }

	  private static class AsapiExceptionStandardSchemeFactory implements SchemeFactory {
	    public AsapiExceptionStandardScheme getScheme() {
	      return new AsapiExceptionStandardScheme();
	    }
	  }

	  private static class AsapiExceptionStandardScheme extends StandardScheme<AsapiException> {

	    public void read(org.apache.thrift.protocol.TProtocol iprot, AsapiException struct) throws org.apache.thrift.TException {
	      org.apache.thrift.protocol.TField schemeField;
	      iprot.readStructBegin();
	      while (true)
	      {
	        schemeField = iprot.readFieldBegin();
	        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
	          break;
	        }
	        switch (schemeField.id) {
	          case 1: // NUMBER
	            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
	              struct.number = iprot.readI32();
	              struct.setNumberIsSet(true);
	            } else { 
	              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
	            }
	            break;
	          case 2: // DESCRIPTION
	            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
	              struct.description = iprot.readString();
	              struct.setDescriptionIsSet(true);
	            } else { 
	              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
	            }
	            break;
	          default:
	            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
	        }
	        iprot.readFieldEnd();
	      }
	      iprot.readStructEnd();

	      // check for required fields of primitive type, which can't be checked in the validate method
	      struct.validate();
	    }

	    public void write(org.apache.thrift.protocol.TProtocol oprot, AsapiException struct) throws org.apache.thrift.TException {
	      struct.validate();

	      oprot.writeStructBegin(STRUCT_DESC);
	      oprot.writeFieldBegin(NUMBER_FIELD_DESC);
	      oprot.writeI32(struct.number);
	      oprot.writeFieldEnd();
	      if (struct.description != null) {
	        oprot.writeFieldBegin(DESCRIPTION_FIELD_DESC);
	        oprot.writeString(struct.description);
	        oprot.writeFieldEnd();
	      }
	      oprot.writeFieldStop();
	      oprot.writeStructEnd();
	    }

	  }

	  private static class AsapiExceptionTupleSchemeFactory implements SchemeFactory {
	    public AsapiExceptionTupleScheme getScheme() {
	      return new AsapiExceptionTupleScheme();
	    }
	  }

	  private static class AsapiExceptionTupleScheme extends TupleScheme<AsapiException> {

	    @Override
	    public void write(org.apache.thrift.protocol.TProtocol prot, AsapiException struct) throws org.apache.thrift.TException {
	      TTupleProtocol oprot = (TTupleProtocol) prot;
	      BitSet optionals = new BitSet();
	      if (struct.isSetNumber()) {
	        optionals.set(0);
	      }
	      if (struct.isSetDescription()) {
	        optionals.set(1);
	      }
	      oprot.writeBitSet(optionals, 2);
	      if (struct.isSetNumber()) {
	        oprot.writeI32(struct.number);
	      }
	      if (struct.isSetDescription()) {
	        oprot.writeString(struct.description);
	      }
	    }

	    @Override
	    public void read(org.apache.thrift.protocol.TProtocol prot, AsapiException struct) throws org.apache.thrift.TException {
	      TTupleProtocol iprot = (TTupleProtocol) prot;
	      BitSet incoming = iprot.readBitSet(2);
	      if (incoming.get(0)) {
	        struct.number = iprot.readI32();
	        struct.setNumberIsSet(true);
	      }
	      if (incoming.get(1)) {
	        struct.description = iprot.readString();
	        struct.setDescriptionIsSet(true);
	      }
	    }
	  }

	}

