/*
 *    AsTeRICS - Assistive Technology Rapid Integration and Construction Set
 * 
 * 
 *        d8888      88888888888       8888888b.  8888888 .d8888b.   .d8888b. 
 *       d88888          888           888   Y88b   888  d88P  Y88b d88P  Y88b
 *      d88P888          888           888    888   888  888    888 Y88b.     
 *     d88P 888 .d8888b  888   .d88b.  888   d88P   888  888         "Y888b.  
 *    d88P  888 88K      888  d8P  Y8b 8888888P"    888  888            "Y88b.
 *   d88P   888 "Y8888b. 888  88888888 888 T88b     888  888    888       "888
 *  d8888888888      X88 888  Y8b.     888  T88b    888  Y88b  d88P Y88b  d88P
 * d88P     888  88888P' 888   "Y8888  888   T88b 8888888 "Y8888P"   "Y8888P" 
 *
 *
 *                    homepage: http://www.asterics.org 
 *
 *     This project has been partly funded by the European Commission, 
 *                      Grant Agreement Number 247730
 *  
 *  
 *         Dual License: MIT or GPL v3.0 with "CLASSPATH" exception
 *         (please refer to the folder LICENSE)
 * 
 */
 
/**
 * @file JNIcomputebandpower.h
 *
 * @author Javier Acedo
 * @date 20/08/2010
 * @version 1.0
 *
 * @brief JNI functions that interface the simple signal processing functions
 *
 **/

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_starlab_signalprocessing_jni_JNIcomputebandpower */

#ifndef _Included_com_starlab_component_processor_jni_JNIcomputebandpower
#define _Included_com_starlab_component_processor_jni_JNIcomputebandpower
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_starlab_signalprocessing_jni_JNIcomputebandpower
 * Method:    nativeCBPInitialization
 * Signature: ()V
 */
/**
 * JNI parse of the native CBP_initialization function
 **/
JNIEXPORT void JNICALL Java_com_starlab_component_processor_jni_JNIcomputebandpower_nativeCBPInitialization
  (JNIEnv *, jobject);

/*
 * Class:     com_starlab_signalprocessing_jni_JNIcomputebandpower
 * Method:    nativeCBPImplementation
 * Signature: ([DI[D)V
 */
/**
 * JNI parse of the native CBP_implementation function
 **/
JNIEXPORT void JNICALL Java_com_starlab_component_processor_jni_JNIcomputebandpower_nativeCBPImplementation
  (JNIEnv *, jobject, jdoubleArray, jint, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
