/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class eu_asterics_component_actuator_syntheticvoice_SyntheticVoiceBridge */

#ifndef _Included_eu_asterics_component_actuator_syntheticvoice_SyntheticVoiceBridge
#define _Included_eu_asterics_component_actuator_syntheticvoice_SyntheticVoiceBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     eu_asterics_component_actuator_syntheticvoice_SyntheticVoiceBridge
 * Method:    activate
 * Signature: (IILjava/lang/String;Z)I
 */
JNIEXPORT jint JNICALL Java_eu_asterics_component_actuator_syntheticvoice_SyntheticVoiceBridge_activate
  (JNIEnv *, jobject, jint, jint, jstring, jboolean);

/*
 * Class:     eu_asterics_component_actuator_syntheticvoice_SyntheticVoiceBridge
 * Method:    deactivate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_eu_asterics_component_actuator_syntheticvoice_SyntheticVoiceBridge_deactivate
  (JNIEnv *, jobject);

/*
 * Class:     eu_asterics_component_actuator_syntheticvoice_SyntheticVoiceBridge
 * Method:    speech
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_eu_asterics_component_actuator_syntheticvoice_SyntheticVoiceBridge_speech
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
