/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class eu_asterics_component_sensor_tobii4cheadtracker_Bridge */

#ifndef _Included_eu_asterics_component_sensor_tobii4cheadtracker_Bridge
#define _Included_eu_asterics_component_sensor_tobii4cheadtracker_Bridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     eu_asterics_component_sensor_tobii4cheadtracker_Bridge
 * Method:    activate
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_eu_asterics_component_sensor_tobii4cheadtracker_Bridge_activate
  (JNIEnv *, jobject, jstring);

/*
 * Class:     eu_asterics_component_sensor_tobii4cheadtracker_Bridge
 * Method:    main_loop
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_eu_asterics_component_sensor_tobii4cheadtracker_Bridge_main_1loop
  (JNIEnv *, jobject);

/*
 * Class:     eu_asterics_component_sensor_tobii4cheadtracker_Bridge
 * Method:    deactivate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_eu_asterics_component_sensor_tobii4cheadtracker_Bridge_deactivate
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
