
/*
 *    AsTeRICS - Assistive Technology Rapid Integration and Construction Set
 * 
 * 
 *        d8888      88888888888       8888888b.  8888888 .d8888b.   .d8888b. 
 *       d88888          888           888   Y88b   888  d88P  Y88b d88P  Y88b
 *      d88P888          888           888    888   888  888    888 Y88b.     
 *     d88P 888 .d8888b  888   .d88b.  888   d88P   888  888         "Y888b.  
 *    d88P  888 88K      888  d8P  Y8b 8888888P"    888  888            "Y88b.
 *   d88P   888 "Y8888b. 888  88888888 888 T88b     888  888    888       "888
 *  d8888888888      X88 888  Y8b.     888  T88b    888  Y88b  d88P Y88b  d88P
 * d88P     888  88888P' 888   "Y8888  888   T88b 8888888 "Y8888P"   "Y8888P" 
 *
 *
 *                    homepage: http://www.asterics.org 
 *
 *     This project has been partly funded by the European Commission, 
 *                      Grant Agreement Number 247730
 *  
 *  
 *    License: GPL v3.0 (GNU General Public License Version 3.0)
 *                 http://www.gnu.org/licenses/gpl.html
 * 
 */

/**
 * @file JNIderivative.h
 *
 * @author Javier Acedo
 * @date 20/08/2010
 * @version 1.0
 *
 * @brief JNI functions that interface the simple signal processing functions
 *
 **/

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_starlab_signalprocessing_jni_JNIderivative */

#ifndef _Included_com_starlab_component_processor_jni_JNIderivative
#define _Included_com_starlab_component_processor_jni_JNIderivative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_starlab_signalprocessing_jni_JNIderivative
 * Method:    nativeDerivativeNew
 * Signature: ()I
 */
/**
 * JNI parse of the native Derivative_new function
 **/
JNIEXPORT jint JNICALL Java_com_starlab_component_processor_jni_JNIderivative_nativeDerivativeNew
  (JNIEnv *env, jobject obj);

/*
 * Class:     com_starlab_signalprocessing_jni_JNIderivative
 * Method:    nativeDerivativeDelete
 * Signature: (I)I
 */
/**
 * JNI parse of the native Derivative_delete function
 **/
JNIEXPORT jint JNICALL Java_com_starlab_component_processor_jni_JNIderivative_nativeDerivativeDelete
  (JNIEnv *env, jobject obj, jint id);

/*
 * Class:     com_starlab_signalprocessing_jni_JNIderivative
 * Method:    nativeDerivativeReset
 * Signature: ()V
 */
/**
 * JNI parse of the native Derivative_reset function
 **/
JNIEXPORT void JNICALL Java_com_starlab_component_processor_jni_JNIderivative_nativeDerivativeReset
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_starlab_signalprocessing_jni_JNIderivative
 * Method:    nativeGetSampleFrequency
 * Signature: ()I
 */
/**
 * JNI parse of the native getSampleFrequency function
 **/
JNIEXPORT jint JNICALL Java_com_starlab_component_processor_jni_JNIderivative_nativeGetSampleFrequency
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_starlab_signalprocessing_jni_JNIderivative
 * Method:    nativeSetSampleFrequency
 * Signature: (I)V
 */
/**
 * JNI parse of the native setSampleFrequency function
 **/
JNIEXPORT jint JNICALL Java_com_starlab_component_processor_jni_JNIderivative_nativeSetSampleFrequency
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_starlab_signalprocessing_jni_JNIderivative
 * Method:    nativeDerivative
 * Signature: (D)D
 */
/**
 * JNI parse of the native Derivative function
 **/
JNIEXPORT jdouble JNICALL Java_com_starlab_component_processor_jni_JNIderivative_nativeDerivative
  (JNIEnv *, jobject, jint, jdouble);

#ifdef __cplusplus
}
#endif
#endif
