//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by itmes.rc
//
#define IDS_APP_TITLE                   103
#define IDM_ABOUT                       104
#define IDS_HELLO                       106
#define IDI_ITMES                       107
#define IDI_SMALL                       108
#define IDC_ITMES                       109
#define IDC_ITEMS                       109
#define IDR_MAINFRAME                   128
#define IDD_BROWSERDIALOG               130
#define IDB_BACKGROUND                  151
#define IDC_EMAIL                       1005
#define IDC_KAUFLIST                    1008
#define IDC_IPLIST                      1008
#define IDC_PREV                        1009
#define IDC_ADD_IP                      1009
#define IDC_NEXT                        1010
#define IDC_OPLIST                      1010
#define IDC_FIRST                       1011
#define IDC_ADD_OP                      1011
#define IDC_LAST                        1012
#define IDC_ELPLIST                     1012
#define IDC_ADD_ELP                     1013
#define IDC_ETPLIST                     1014
#define IDC_ADR                         1015
#define IDC_ADD_ETP                     1015
#define IDC_ZUSATZ                      1016
#define IDC_PLUGINNAME                  1016
#define IDC_AREPATH                     1017
#define IDC_PROPLIST                    1018
#define IDC_CREATE_PLUGIN               1019
#define IDC_SEARCH_EMAIL                1020
#define IDC_ADD_PROP                    1020
#define IDC_DEL_IP                      1021
#define IDC_DEL_OP                      1022
#define IDC_DEL_ELP                     1023
#define IDC_DEL_ETP                     1024
#define IDC_DEL_PROP                    1025
#define IDC_ABHOLUNG                    1026
#define IDC_HASGUI                      1026
#define IDC_SINGLETON                   1027
#define IDC_ENGLISH                     1028
#define IDC_HASCIM                      1028
#define IDC_SUMME                       1029
#define IDC_HASCIM2                     1029
#define IDC_HASJNI                      1029
#define IDC_PLUGINNAME2                 1030
#define IDC_SUBCATEGORY                 1030
#define IDC_DEL_ETP2                    1031
#define IDC_CHOOSEDIR                   1031
#define IDC_KUND_NEW                    1032
#define IDC_KUND_RECHNUNG               1033
#define IDC_KUND_ALL                    1034
#define IDC_EBAY_ADDRESS                1036
#define IDC_KNR                         1037
#define IDC_SEARCH_EBAYNUM              1038
#define IDC_BILD_NEU                    1042
#define IDC_IPNAME                      1042
#define IDC_PREIS_NEU                   1043
#define IDC_OPNAME                      1043
#define IDC_VERKAUF_NEU                 1044
#define IDC_ELPNAME                     1044
#define IDC_SEARCH_BILD                 1045
#define IDC_ETPNAME                     1045
#define IDC_EBAYNUM                     1046
#define IDC_PROPNAME                    1046
#define IDC_GUI_XSIZE                   1047
#define IDC_GUI_YSIZE                   1048
#define IDC_PROPCOMBO_ENTRIES           1049
#define IDC_IPDESC                      1050
#define IDC_OPDESC                      1051
#define IDC_ELPDESC                     1052
#define IDC_ETPDESC                     1053
#define IDC_PROPDESC                    1054
#define IDC_PLUGINDESC                  1055
#define IDC_PROPVALUE                   1056
#define IDC_SUCH_WEITER                 1058
#define IDC_SUCHWORT                    1077
#define IDC_SUCHKUNDEN                  1079
#define IDC_SUCHARTIKEL                 1080
#define IDC_SUCHRECHNUNG                1081
#define IDC_BROWSER                     1111
#define IDC_BUTTON1                     1150
#define IDC_IPTYPECOMBO                 1151
#define IDC_OPTYPECOMBO                 1152
#define IDC_PLUGINTYPECOMBO             1153
#define IDC_PROPTYPECOMBO               1154
#define IDM_PROCESS                     32771
#define IDM_ABHOL                       32773
#define IDM_VERKAUF                     32774
#define IDM_SEARCH_RECHNUNG             32776
#define IDM_NEUKUNDE                    32778
#define IDM_DELKUNDE                    32779
#define IDM_SEARCH_EBAYNUM              32780
#define IDM_ZAHLUNGSEMAIL               32781
#define IDM_EXITALL                     32783
#define IDM_EMAILS                      32784
#define IDM_INFOMAIL                    32787
#define IDM_ABHOLMAIL                   32788
#define IDM_MAHNUNGSMAIL                32789
#define IDM_RECHNUNGSVORLAGE            32790
#define IDM_INFOMAIL_ENGL               32791
#define IDM_REPORTBILL                  32793
#define IDM_SORTKUNDEN                  32795
#define IDM_REPORTVERK                  32796
#define IDM_OPTIONS                     32797
#define IDM_ARTIKELBROWSER              32801
#define IDM_EXITSAVE                    32802
#define IDM_LISTKUNDEN                  32803
#define IDM_SAV_DATABASE                32804
#define IDM_RESTORE_DATABASE            32805
#define IDM_DELOLD                      32806
#define IDM_REPORTKUNDEN                32807
#define ID_EXIT                         32808
#define IDM_EXIT                        32809
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        179
#define _APS_NEXT_COMMAND_VALUE         32810
#define _APS_NEXT_CONTROL_VALUE         1156
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
