/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class eu_asterics_component_actuator_gsmmodem_GSMModemBridge */

#ifndef _Included_eu_asterics_component_actuator_gsmmodem_GSMModemBridge
#define _Included_eu_asterics_component_actuator_gsmmodem_GSMModemBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     eu_asterics_component_actuator_gsmmodem_GSMModemBridge
 * Method:    activate
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_eu_asterics_component_actuator_gsmmodem_GSMModemBridge_activate
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     eu_asterics_component_actuator_gsmmodem_GSMModemBridge
 * Method:    sendSMS
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_eu_asterics_component_actuator_gsmmodem_GSMModemBridge_sendSMS
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     eu_asterics_component_actuator_gsmmodem_GSMModemBridge
 * Method:    close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_eu_asterics_component_actuator_gsmmodem_GSMModemBridge_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
