name: Release
on: workflow_dispatch
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install JDK
        uses: actions/setup-java@v3
        with:
          java-version: "8"
          distribution: "zulu"
          java-package: jdk
          architecture: x64
          check-latest: true
      - name: Install ant
        run: sudo apt install ant -y
      - name: Test ant Install
        run: ant -version
