name: Release
on: workflow_dispatch
jobs:
  linux:
    uses: ./.github/workflows/release-linux.yml
    with:
      version: 4.7
      platform: ubuntu-20.04
  windows:
    uses: ./.github/workflows/release-windows.yml
  mac:
    uses: ./.github/workflows/release-mac.yml
