name: Release (macOS)
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version Number"
        required: true
        type: string
      platform:
        description: "Platform Type"
        required: false
        default: macos-latest
        type: choice
        options:
          - macos-latest
          - macos-12
          - macos-11
          - macos-10.15
  workflow_call:
    inputs:
      version:
        description: "Version Number"
        required: true
        type: number
      platform:
        description: "Platform Type"
        default: macos-latest
        required: true
        type: string
env:
  VERSION: ${{ inputs.version }}
  ARTIFACT: AsTeRICS ${{ inputs.version }} (${{ inputs.platform }})
jobs:
  build:
    runs-on: ${{ inputs.platform }}
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install JDK
        uses: actions/setup-java@v3
        with:
          java-version: "8"
          distribution: "zulu"
          java-package: "jdk+fx"
          architecture: "x64"
          check-latest: true
      - name: Move JDK
        run: |
          shopt -s extglob
          mkdir -p $JAVA_HOME/Contents/Home
          cp -r $JAVA_HOME/!(Contents) $JAVA_HOME/Contents/Home/
      - name: Build AsTeRICS
        env:
          JAVA_HOME: ${{ env.JAVA_HOME_8_X64 }}/Contents/Home
        run: ant -buildfile Installer/asterics-are/build.xml deploy -Dfx.deploy.nativeBundles=dmg -DAPE.embedJava=true -Dfx.application.version=$VERSION -Dfx.deploy.verbose=true
      - name: Release .dmg File
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT }}
          path: Installer/asterics-are/build/deploy/bundles/asterics-are-javaembedded-${{ env.VERSION }}.dmg
  install:
    needs: build
    runs-on: macos-latest
    steps:
      - name: Get Software
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.ARTIFACT }}
