name: Release (macOS)
on: workflow_dispatch
env:
  VERSION: 4.5
  ARTIFACT: AsTeRICS 4.5 (macOS)
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install JDK
        uses: actions/setup-java@v3
        with:
          java-version: "8"
          distribution: "zulu"
          java-package: "jdk+fx"
          architecture: "x64"
          check-latest: true
      - name: Move JDK
        run: |
          shopt -s extglob
          mkdir -p $JAVA_HOME/Contents/Home
          cp -r $JAVA_HOME/!(Contents) $JAVA_HOME/Contents/Home/
      - name: Build AsTeRICS
        env:
          JAVA_HOME: ${{ env.JAVA_HOME_8_X64 }}/Contents/Home
        run: ant -buildfile Installer/asterics-are/build.xml deploy -Dfx.deploy.nativeBundles=dmg -DAPE.embedJava=true -Dfx.application.version=$VERSION -Dfx.deploy.verbose=true
      - name: Release .dmg File
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT }}
          path: Installer/asterics-are/build/deploy/bundles/asterics-are-javaembedded-${{ env.VERSION }}.dmg
  install:
    needs: build
    runs-on: macos-latest
    steps:
      - name: Get Software
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.ARTIFACT }}
