name: Release
on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:
    inputs:
      version:
        description: "Version Number"
        required: true
        type: string
      linux:
        description: "Linux Platform Type"
        required: false
        default: ubuntu-latest
        type: choice
        options:
          - ubuntu-latest
          - ubuntu-22.04
          - ubuntu-20.04
          - ubuntu-18.04
      windows:
        description: "Windows Platform Type"
        required: false
        default: windows-latest
        type: choice
        options:
          - windows-latest
          - windows-2022
          - windows-2019
      macOS:
        description: "macOS Platform Type"
        required: false
        default: macos-latest
        type: choice
        options:
          - macos-latest
          - macos-12
          - macos-11
          - macos-10.15
jobs:
  linux:
    uses: ./.github/workflows/release-linux.yml
    with:
      version: ${{ inputs.version }}
      platform: ${{ inputs.linux }}
  windows:
    uses: ./.github/workflows/release-windows.yml
    with:
      version: ${{ inputs.version }}
      platform: ${{ inputs.windows }}
  mac:
    uses: ./.github/workflows/release-mac.yml
    with:
      version: ${{ inputs.version }}
      platform: ${{ inputs.macOS }}
