name: Release (macOS)
on: workflow_dispatch
env:
  VERSION: 4.5
jobs:
  mac:
    runs-on: macos-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install JDK
        uses: actions/setup-java@v3
        with:
          java-version: "8"
          distribution: "zulu"
          java-package: "jdk+fx"
          architecture: "x64"
          check-latest: true
      - name: Install ant
        run: brew install ant
      - name: Log environment variables & JAVA_HOME
        run: |
          echo $JAVA_HOME
          printenv
      - name: Build AsTeRICS
        run: ant -buildfile Installer/asterics-are/build.xml deploy -Dfx.deploy.nativeBundles=dmg -DAPE.embedJava=true -Dfx.application.version=$VERSION -Dfx.deploy.verbose=true
      - name: Release .dmg File
        uses: actions/upload-artifact@v3
        with:
          name: AsTeRICS ${{ env.VERSION }} (mac)
          path: Installer/asterics-are/build/deploy/bundles/asterics-are-${{ env.VERSION }}.dmg
